package com.codeleb.insights.domain.model;

import com.codeleb.insights.domain.exception.BusinessRuleViolationException;

import java.math.BigDecimal;

/**
 * Purpose: Represents a rich domain insight generated by a prediction strategy
 * for a specific customer.
 * Strict Constraints: Pure Java record with enterprise validation.
 */
public record ActionableInsight(
        String customerId,
        String type,
        String description,
        BigDecimal value,
        double confidenceScore) {
    public ActionableInsight {
        if (customerId == null || customerId.isBlank()) {
            throw new BusinessRuleViolationException("ActionableInsight customerId cannot be null or blank");
        }
        if (type == null || type.isBlank()) {
            throw new BusinessRuleViolationException("ActionableInsight type cannot be null or blank");
        }
        if (confidenceScore < 0.0 || confidenceScore > 1.0) {
            throw new BusinessRuleViolationException("ActionableInsight confidenceScore must be between 0.0 and 1.0");
        }
    }
}
